sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: aTymYQWr+mWNQYkrV6gWA/BeJ7KtJTfVUKvXHv86pZUv/seo7XShtFG8nmooN0y1zVJ+AB8r2UhN4w/XPOwx8i+7kzTEwZkQDALJ2x7ePp5HPrpKOrFd6WfYn0LbM6kfHNxsBBIwCqMZ1S0xrsW0LzWDT2fm/UhLGmCmL4S56NNj72X3gDyBjtI5csG+BQNjlTxS9UKMO2Azw5eZ2vuOoRF7/sEA8LoL2ZY/ctbZ9rVdHiHq2UEy9SohiUsudikSoCTqsw7CxFXRAg3qIiGos6y1eyC/ZO788ENDNxf13njsSwZrJd0sPOacDO2CtPGZ2ieKWevm+biwBVHyVxgoa2rq4yxPAgmNBHzCZQb3QBQR2VoHeiudSIovvdSZzKaFO91Dd7QdfVAGUeLdFxWBHRFFG/V1RkLx98zBlOaJ6WJFpX9iZcIE1PJSarxU4mc4CeS64qjCGXQ1R5Uu6XDQY+BGU8xmrZPx24dwFGhk1hvhYlcPNCIcDmp2l13c7q9p+CYAB1bRJX8VD2rBICBOr35Z4TXP4fQ6Ic3s7Ni1K9c4h1qBigIw5ct4ACv0Ht1ntfn6IVW8QsvdyDAQiXUkXAJp+DAC+c3u5ipyzxr5QswOE/xu3JlG+uWQ2k5lnofAWfYFWzWWcfeNZ/OIO2zk2CeRh3kdmG52UzLTkD2Cg2g=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Mark-Twain-s-Letters---Volume-5--1901-1906-_3197
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy